# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Pull Request

on:
  pull_request:
    branches: [ 3.x ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
    - name: Set up JDK 8
      uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
      with:
        distribution: 'zulu'
        java-version: '8'
    - name: Cache Gradle packages
      uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 # v4.1.0
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-1-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle-1-
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build RxJava
      run: ./gradlew build --stacktrace
    - name: Upload to Codecov  
      uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
    - name: Generate Javadoc
      run: ./gradlew javadoc --stacktrace
