# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: JDK 11

on:
  push:
    branches: [ 3.x ]
  pull_request:
    branches: [ 3.x ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
    - name: Set up JDK 11
      uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Cache Gradle packages
      uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-1-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle-1-
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Verify generated module-info
      run: ./gradlew -PjavaCompatibility=9 jar
    - name: Build RxJava
      run: ./gradlew build --stacktrace
    - name: Generate Javadoc
      run: ./gradlew javadoc --stacktrace
