name: Scheduled Test Run

on:
  push:
    branches:
      - 3.x  # Puoi modificare il nome del branch se necessario

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Azione per clonare il repository
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17.0.10'  # Specifica la versione di Java da utilizzare

      - name: Setup Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: '7.6.4'  # Specifica la versione di Gradle da utilizzare

      - name: Set execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle tests
        run: ./gradlew clean

      - name: Run Gradle tests
        run: ./gradlew test

      - name: Configure Git
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"

      - name: Commit coverage matrix changes
        run: |
          git add coverage-matrix.json  # Updated path to the coverage matrix
          git commit -m "Update coverage matrix" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin main  # Modify the branch name if necessary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token to authenticate
